import type { DomainKey } from '@arca/scoring';
import type { Question } from './types.js';

/** Etiquetas de dominio que ve el usuario final. */
export const DOMAIN_LABELS: Record<DomainKey, string> = {
  governance: 'AI Governance & Policy',
  tools: 'AI Tools in Use',
  oversight: 'Human Oversight',
  data_protection: 'Data Protection',
  training: 'Training & Competency',
  incident_preparedness: 'Incident History & Preparedness',
};

/**
 * Banco de preguntas: data versionada, nunca lógica. Los option ids son los mismos que usa
 * la tabla de puntaje de @arca/scoring, así que agregar una opción exige actualizar ambos.
 */
export const QUESTION_BANK: Question[] = [
  {
    id: 'Q1.1',
    domain: 'governance',
    domain_label: DOMAIN_LABELS.governance,
    text: 'Does your firm have a written policy governing the use of AI tools?',
    type: 'single_select',
    options: [
      { id: 'formal_documented', text: 'Yes, a formal documented policy' },
      { id: 'informal', text: 'Yes, but informal or unwritten guidance' },
      { id: 'in_development', text: 'It is currently being developed' },
      { id: 'no_policy', text: 'No policy in place' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q1.2',
    domain: 'governance',
    domain_label: DOMAIN_LABELS.governance,
    text: 'Which of these aspects does your AI policy cover?',
    type: 'multi_select',
    options: [
      { id: 'approved_tools', text: 'Approved AI tools for professional use' },
      { id: 'data_rules', text: 'What data types can and cannot be entered' },
      { id: 'review_process', text: 'Mandatory output review process' },
      { id: 'client_disclosure', text: 'Client disclosure requirement' },
      { id: 'training', text: 'Mandatory training program' },
      { id: 'incidents', text: 'Incident reporting protocol' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q1.3',
    domain: 'governance',
    domain_label: DOMAIN_LABELS.governance,
    text: 'Who is accountable for AI governance at the firm?',
    type: 'single_select',
    options: [
      { id: 'committee', text: 'A dedicated committee or governance body' },
      { id: 'specific_partner', text: 'A specific partner' },
      { id: 'it_department', text: 'The IT department' },
      { id: 'individual', text: 'One individual, informally' },
      { id: 'nobody', text: 'Nobody is formally accountable' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q2.1',
    domain: 'tools',
    domain_label: DOMAIN_LABELS.tools,
    text: 'Which AI tools does the firm use for legal work?',
    type: 'single_select',
    options: [
      { id: 'legal_enterprise', text: 'Legal-specific enterprise tools (CoCounsel, Harvey, Clio AI)' },
      { id: 'enterprise_api', text: 'Enterprise AI with admin controls (Copilot for Business, Azure OpenAI)' },
      { id: 'commercial', text: 'Commercial consumer plans (ChatGPT Plus or Team)' },
      { id: 'public_free', text: 'Free public versions' },
      { id: 'none', text: 'The firm does not use AI tools' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q2.2',
    domain: 'tools',
    domain_label: DOMAIN_LABELS.tools,
    text: 'Are AI tools used in an environment controlled by the firm, or does each attorney access them directly?',
    type: 'single_select',
    options: [
      { id: 'enterprise_controlled', text: 'Enterprise instance controlled by the firm' },
      { id: 'api_controlled', text: 'API with access controls' },
      { id: 'commercial_accounts', text: 'Each attorney with their own account (Team or Business)' },
      { id: 'public_free', text: 'Free public version' },
      { id: 'dont_know', text: 'Do not know' },
    ],
    info_tooltip:
      'Answering "Do not know" means nobody at the firm has visibility into how AI tools are used. We treat that as a significant risk factor.',
  },
  {
    id: 'Q2.3',
    domain: 'tools',
    domain_label: DOMAIN_LABELS.tools,
    text: 'How does the firm prevent confidential client data from being entered into AI tools?',
    type: 'single_select',
    options: [
      { id: 'technical_controls', text: 'Technical controls block it (DLP, gateway or redaction)' },
      { id: 'policy_only', text: 'A written policy prohibits it' },
      { id: 'anonymized', text: 'Data is anonymized before use' },
      { id: 'real_data', text: 'Real client data is entered as-is' },
      { id: 'no_visibility', text: 'We have no visibility into what is entered' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q3.1',
    domain: 'oversight',
    domain_label: DOMAIN_LABELS.oversight,
    text: 'What review process applies to AI-generated work product before it leaves the firm?',
    type: 'single_select',
    options: [
      { id: 'peer_review', text: 'Mandatory review by a second attorney' },
      { id: 'self_review_checklist', text: 'Self-review against a documented checklist' },
      { id: 'informal', text: 'Informal review, with no defined process' },
      { id: 'depends_individual', text: 'It depends on the individual attorney' },
      { id: 'no_process', text: 'No review process' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q3.2',
    domain: 'oversight',
    domain_label: DOMAIN_LABELS.oversight,
    text: 'How are legal citations produced with AI verified?',
    type: 'single_select',
    options: [
      { id: 'tools_always', text: 'Always verified in Westlaw or Lexis' },
      { id: 'manual_always', text: 'Always verified manually against primary sources' },
      { id: 'generally', text: 'Generally verified, but not always' },
      { id: 'rarely', text: 'Rarely verified' },
      { id: 'no_protocol', text: 'No verification protocol' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q3.3',
    domain: 'oversight',
    domain_label: DOMAIN_LABELS.oversight,
    text: 'Does the firm disclose its use of AI to clients?',
    type: 'single_select',
    options: [
      { id: 'always_engagement', text: 'Always, in the engagement letter' },
      { id: 'case_by_case', text: 'Case by case' },
      { id: 'only_if_asked', text: 'Only if the client asks' },
      { id: 'never', text: 'Never' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q4.1',
    domain: 'data_protection',
    domain_label: DOMAIN_LABELS.data_protection,
    text: 'What protocol governs which client data may reach an AI provider?',
    type: 'single_select',
    options: [
      { id: 'technical_controls', text: 'Technical controls enforce it (DLP or access rules)' },
      { id: 'guidelines', text: 'Written guidelines, enforced by staff' },
      { id: 'in_development', text: 'A protocol is being developed' },
      { id: 'none', text: 'No protocol' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q4.2',
    domain: 'data_protection',
    domain_label: DOMAIN_LABELS.data_protection,
    text: 'Is client data processed by AI providers outside the United States?',
    type: 'single_select',
    options: [
      { id: 'us_only', text: 'No, processing is contractually limited to the US' },
      { id: 'dpa_signed', text: 'It may be, and a data processing agreement is signed' },
      { id: 'no_agreement', text: 'It may be, with no agreement in place' },
      { id: 'dont_know', text: 'Do not know' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q5.1',
    domain: 'training',
    domain_label: DOMAIN_LABELS.training,
    text: 'What AI training has the firm delivered to its attorneys?',
    type: 'single_select',
    options: [
      { id: 'mandatory_recurring', text: 'Mandatory recurring training' },
      { id: 'once', text: 'A one-time session' },
      { id: 'optional', text: 'Optional training' },
      { id: 'planned', text: 'Training is planned but not delivered yet' },
      { id: 'none', text: 'No training' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q5.2',
    domain: 'training',
    domain_label: DOMAIN_LABELS.training,
    text: 'How does the firm evaluate attorney competency with AI tools?',
    type: 'single_select',
    options: [
      { id: 'formal_assessment', text: 'Formal assessment after training' },
      { id: 'supervision_onboarding', text: 'Supervision during onboarding' },
      { id: 'individual_judgment', text: 'Left to individual judgment' },
      { id: 'no_evaluation', text: 'No evaluation' },
    ],
    info_tooltip: null,
  },
  {
    id: 'Q6.1',
    domain: 'incident_preparedness',
    domain_label: DOMAIN_LABELS.incident_preparedness,
    text: 'Has the firm experienced any of these AI-related incidents in the last 24 months?',
    type: 'multi_select',
    options: [
      { id: 'none', text: 'No incidents' },
      { id: 'doc_error', text: 'An error in an AI-drafted document' },
      { id: 'citation_error', text: 'A fabricated or incorrect legal citation' },
      { id: 'data_exposure', text: 'Confidential data exposed to an AI provider' },
      { id: 'client_complaint', text: 'A client complaint related to AI use' },
      { id: 'regulatory_investigation', text: 'A regulatory or bar investigation' },
    ],
    info_tooltip:
      'An active regulatory investigation makes the firm ineligible for coverage at this time.',
  },
  {
    id: 'Q6.2',
    domain: 'incident_preparedness',
    domain_label: DOMAIN_LABELS.incident_preparedness,
    text: 'Does the firm have an incident response plan for AI-related errors?',
    type: 'single_select',
    options: [
      { id: 'documented_tested', text: 'Documented and rehearsed' },
      { id: 'documented_not_tested', text: 'Documented but never rehearsed' },
      { id: 'informal', text: 'Informal and undocumented' },
      { id: 'none', text: 'No plan' },
    ],
    info_tooltip: null,
  },
];

export const QUESTIONS_BY_ID: Record<string, Question> = Object.fromEntries(
  QUESTION_BANK.map((q) => [q.id, q]),
);
